update "start your own model" in readme with typo checks
HolgerBartel/Causing pull request #49
Opened 2022-01-06 07:32 UTC by salistha-shakya

2022-01-06 11:59 UTC, Holger-Bartel requested changes
Thanks Salistha, for going over it so carefully.

One more thing: Did you also regenerated the graphs in this repository and checked that they didn't change? Please check for both, the simple example and the wages example, thanks.

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
> +are captured by a single bias, one at time. Biases therefore are just one simple way
"one at a time"

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
> +    - _xvars_: exogenous variables in desired order
remove "in desired order": there is no required order for xvars, we just need an ordering for the yvars

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
> +    - _equations_: previously defined equations
Just to be sure: We have .TSV files just in the private repository? (They are requiring some more information.)
https://github.com/realrate/RealRate-Private/blob/develop/industry/de_life/model.tsv

Sorry, no .TSV file here https://github.com/realrate/Causing/blob/develop/causing/examples/models.py.

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
>  Note that in Sympy some operators are special, e.g. Max() instead of max().
Move up and add to the bullet point directly above: "Note that in Sympy some operators are special, e.g. Max() instead of max()."

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
> +- In _estimate_input_, the dictionary to be returned, further specify
"In _estimate_input_, the inputs to be used for estimation, further specify"

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
> +The files ADE, ATE, AME contains the average effects based on the median _xdat_ observation as well as the estimated effects (EDE, ETE, EME) using
contain instead of contains

2022-01-06 11:59 UTC, Holger-Bartel commented on README.md
> +The graphs ED0, ET0, EM0 contains the t-values graphs with respect to zero
contain instead of contains

2022-01-06 13:24 UTC, salistha-shakya commented
I will tally the graphs and resolve other issues too.

2022-01-07 08:19 UTC, karlb approved these changes
Looks good!

2022-01-07 12:17 UTC, Holger-Bartel approved these changes
@salistha-shakya OK, so just the estimated effects changed:
Estimated effects | EDE | ETE | EME

t-values wrt. zero | ED0 | ET0 | EM0
t-values wrt. model | ED1 | ET1 | EM1

The changes are not to big. I accept them. Please check the text again, if old number are still used in the text.

Then please create a new issue: Causing Test Cases.
There we should check the numerical output of the simple example model and the wage example. This should prevent us from having such an unexplainable deviance again. Put that issue on the board. Thanks.

2022-01-07 12:26 UTC, karlb commented
> Put that issue on the board.

Just in case you haven't seen it yet, "the board" means https://github.com/orgs/realrate/projects/1.

2022-01-12 06:09 UTC, merged