fix number format in graph for de
HolgerBartel/Causing pull request #58
Opened 2022-02-08 10:36 UTC by salistha-shakya

2022-02-08 11:02 UTC, salistha-shakya commented
de_health:
[DH4001_2021_Continentale_Kranken.pdf](https://github.com/realrate/Causing/files/8023157/DH4001_2021_Continentale_Kranken.pdf)

de_life:
[DL1001_2021_AachenMuenchener_Leben.pdf](https://github.com/realrate/Causing/files/8023164/DL1001_2021_AachenMuenchener_Leben.pdf)

2022-02-14 09:25 UTC, karlb requested changes

2022-02-14 09:25 UTC, karlb commented on causing/graph.py
> +        dot_str = dot_str.replace(".", ",")
* There's no concept of an industry in Causing. Causing is generic and should not care about industries, companies, countries, etc. Accepting formatting functions or using locales would be acceptable.
* If we go the hacky way of doing search&replace on the output, then let's do it in realrate-private and not here
* Replacing all dots can easily replace far more than only the decimal points. It should at least check that the dot is part of a number (e.g. a `r'\d[.]\d'` regex).

My suggestion:
Expect that the locale is correctly set before `create_and_save_graph` is called and use https://docs.python.org/3/library/locale.html#locale.format_string for the number formatting in the graph.

2022-02-16 09:15 UTC, karlb approved these changes
Looks good. We can remove `utils.roundec` now, can't we?

2022-02-16 13:11 UTC, merged